services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mtarld\SymbokBundle\Compiler\:
        resource: '../../Compiler/'

    Mtarld\SymbokBundle\Context\:
        resource: '../../Context/'

    Mtarld\SymbokBundle\Factory\:
        resource: '../../Factory/'

    Mtarld\SymbokBundle\MethodGenerator\:
        resource: '../../MethodGenerator/'

    Mtarld\SymbokBundle\Service\:
        resource: '../../Service/'
        public: true

    Mtarld\SymbokBundle\Tags\Updater:
        public: true
